<Acceder>:
    FloatLayout:
        Label:
            text: "Inicio de sesión"
            font_size: "20sp"
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.9, "center_x": 0.5}
        TextInput:
            id: username_input
            hint_text: "Nombre de usuario"
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.75, "center_x": 0.5}
        TextInput:
            id: password_input
            hint_text: "Contraseña"
            password: True
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.6, "center_x": 0.5}
        Button:
            text: "Acceder"
            size_hint: 0.4, 0.1
            pos_hint: {"top": 0.45, "center_x": 0.3}
            on_release: app.login_user(username_input.text, password_input.text)
        Button:
            text: "Registrarse"
            size_hint: 0.4, 0.1
            pos_hint: {"top": 0.45, "center_x": 0.7}
            on_release: app.PantallaRegistro()
<Registro>:
    FloatLayout:
        Label:
            text: "Registro de usuario"
            font_size: "20sp"
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.9, "center_x": 0.5}
        TextInput:
            id: username_input
            hint_text: "Nombre de usuario"
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.75, "center_x": 0.5}
        TextInput:
            id: email_input
            hint_text: "Correo electrónico"
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.6, "center_x": 0.5}
        TextInput:
            id: password_input
            hint_text: "Contraseña"
            password: True
            size_hint: 0.8, 0.1
            pos_hint: {"top": 0.45, "center_x": 0.5}
        Button:
            text: "Registrarse"
            size_hint: 0.4, 0.1
            pos_hint: {"top": 0.3, "center_x": 0.5}
            on_release: app.register_user(username_input.text, email_input.text, password_input.text)
